/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.kajih;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class rxJavaAppTest {
  @Test
  void appHasAGreeting() {
    RxJavaApp classUnderTest = new RxJavaApp();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
